controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - base_stand__base
      - base__shoulder
      - shoulder__elbow
      - elbow__end_effector
initial:  # Define initial robot poses per group
  - group: arm
    pose: ready