controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - base_stand__base
      - base__shoulder
      - shoulder__elbow
      - elbow__end_effector
  - name: joint_group_position_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - base_stand__base
      - base__shoulder
      - shoulder__elbow
      - elbow__end_effector


arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - base_stand__base
    - base__shoulder
    - shoulder__elbow
    - elbow__end_effector
  gains:
    base_stand__base:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    base__shoulder:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    shoulder__elbow:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elbow__end_effector:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
joint_group_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
    - base_stand__base
    - base__shoulder
    - shoulder__elbow
    - elbow__end_effector
  gains:
    base_stand__base:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    base__shoulder:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    shoulder__elbow:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elbow__end_effector:
      p: 100
      d: 1
      i: 1
      i_clamp: 1